name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Setup Gradle (latest)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Build project
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # Run unit tests
      - name: Run Tests
        run: ./gradlew test

      # Upload release APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
